# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    engine.admin.menu.voter.request:
        class: Engine\AdminBundle\Menu\RequestVoter
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.voter }
    engine.user.annotation_driver:
        class: Engine\UserBundle\Annotations\Driver\AnnotationDriver
        tags:
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}
        arguments: ["@annotation_reader", "@security.helper"]